import numpy as np
import torch

from model import NN


def set_run_seed(seed: int) -> None:
    torch.manual_seed(seed)
    np.random.seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def make_problem(cfg, device, dtype):
    x = torch.linspace(0, 1, cfg.n_points, device=device, dtype=dtype).unsqueeze(-1)

    y = (
        cfg.linear_coef * x
        + cfg.amp0 * torch.sin(cfg.freq0 * torch.pi * x)
        + cfg.amp1 * torch.sin(cfg.freq1 * torch.pi * x)
        + cfg.amp2 * torch.sin(cfg.freq2 * torch.pi * x)
        + cfg.amp3 * torch.sin(cfg.freq3 * torch.pi * x)
    )

    basis = torch.cat(
        [
            x,
            torch.sin(cfg.freq0 * torch.pi * x),
            torch.sin(cfg.freq1 * torch.pi * x),
            torch.sin(cfg.freq2 * torch.pi * x),
            torch.sin(cfg.freq3 * torch.pi * x),
        ],
        dim=1,
    )

    component_names = [
        r"$x$",
        rf"$\sin({cfg.freq0}\pi x)$",
        rf"$\sin({cfg.freq1}\pi x)$",
        rf"$\sin({cfg.freq2}\pi x)$",
        rf"$\sin({cfg.freq3}\pi x)$",
    ]

    target_component_coef = torch.linalg.lstsq(basis, y).solution.squeeze().detach().cpu().numpy()

    return {
        "x": x,
        "y": y,
        "basis": basis,
        "component_names": component_names,
        "target_component_coef": target_component_coef,
    }


def make_problem_NN(cfg, device, dtype, teacher_model=None):
    """Create a problem generated by an NN with the same random-feature form.

    The returned ``basis`` is the teacher's frozen hidden-feature matrix, so
    the target is exactly representable by changing only the output layer.
    Pass the returned ``teacher_model``'s ``fc1`` weights to the student if an
    exact finite-width match is desired.
    """
    x = torch.linspace(0, 1, cfg.n_points, device=device, dtype=dtype).unsqueeze(-1)
    if teacher_model is None:
        teacher_model = NN(
            cfg.input_dim, cfg.hidden_dim, cfg.output_dim, cfg.beta,
            freeze_first_layer=cfg.freeze_first_layer,
        )
        teacher_model = teacher_model.to(device=device, dtype=dtype)

    with torch.no_grad():
        hidden = teacher_model.activation(teacher_model.fc1(x))
        basis = hidden / (cfg.hidden_dim ** cfg.beta)
        y = teacher_model(x)

    component_names = [rf"$\phi_{{{j}}}(x)$" for j in range(basis.shape[1])]
    target_component_coef = teacher_model.fc2.weight.detach().cpu().numpy().reshape(-1)

    return {
        "x": x,
        "y": y,
        "basis": basis,
        "component_names": component_names,
        "target_component_coef": target_component_coef,
        "teacher_model": teacher_model,
    }
